//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectSmile.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientHistory
    {
        public long Id { get; set; }
        public long PatientId { get; set; }
        public string TreatmentDone { get; set; }
        public decimal PaymentDone { get; set; }
        public decimal Balance { get; set; }
        public Nullable<System.DateTime> NextAppointment { get; set; }
        public string AdditionalComment { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
